#!/bin/sh

release="${2:-stable}"
if [ -e /tmp/selections.all ];then
	echo running: 
	xargs -a "/tmp/selections.all" echo apt-get install --no-install-recommends -y -t $release 
	DEBIAN_FRONTEND=noninteractive xargs -a "/tmp/selections.all" apt-get install --no-install-recommends -y -t $release 
fi
rm /tmp/selections.all
