#!/bin/bash
. /bin/load-envd

confd -onetime -backend env

if [ "$1" = "bootstrap" ]; then
	/commands/container-bootstrap
elif [ "$1" = "status" ]; then
	/commands/container-status
elif [ "$1" = "shell" ]; then
	echo "Running shell"
	bash
else
	echo "Starting dinit Periodic..."
	exec /bin/dinit -stop /bin/runit-stop -r /bin/runit-start  
fi
