#!/bin/sh

release="${2:-stable}"

if [ -e /tmp/selections.all ];then
	echo running: 
	xargs -a "/tmp/selections.all" echo apt-get install --no-install-recommends -y -t $release 
	xargs -a "/tmp/selections.all" apt-get install --no-install-recommends -y -t $release 
fi 

#cleanup
rm -rf /var/lib/apt/lists
#rm /tmp/*
apt-get autoremove -y
apt-get clean

rm /etc/apt/apt.conf.d/10-proxy
rm /etc/env.d/10-proxy
