#!/bin/bash

# runs a dir of scripts every 60 minutes 
# and every 24 hours
# not very accurate but does the job
D=0
H=0
M=0


while true; do
	H=0
	while [ $H -lt 23 ]; do
		M=0
		sleep 3600
	
		run-parts --regex '^.*\.sh$' /docker/periodic_hourly.d
		let H=$H+1
	done
	run-parts --regex '^.*\.sh$' /docker/periodic_daily.d
	let D=$D+1
done
		
	
