#!/bin/bash 

export DEBIAN_FRONTEND=noninteractive 
 echo "Europe/Stockholm" > /etc/timezone
	dpkg-reconfigure -f noninteractive tzdata 
	export LANGUAGE=en_US.UTF-8 
	export LANG=en_US.UTF-8 
	export LC_ALL=en_US.UTF-8 
	locale-gen en_US.UTF-8
	dpkg-reconfigure locales

